// import React from 'react';

type ActionsType = {
	LOGIN_REQ : string;
	LOGOUT : string;
	GET_USER : string;
	LOGGED_IN : string;
	LOG_IN_ERR : string;
	LOGOUT_SUCCESS : string;
	CATEGORIES : string;
	CATEGORIES_SUCCESS : string;
	POSTS : string;
	GET_POSTS_SUCCESS: string;
	CREATE_POST: string;
	POST_CREATED: string;
	REDIRECT_HOME: string;
	CREATE_CATEGORY: string;
	CATEGORY_CREATED: string;
	LIKE_POST: string;
	DISLIKE_POST: string;
	UPVOTE_POST: string;
	DOWNVOTE_POST: string;
	COMMENT_POST: string;
	COMMENTS_UPDATE: string;
	POST_REPORT: string;
	POST_SAVE: string;
	POST_SAVED: string;
	SET_SAVED_POSTS : string;
	DELETE_POST : string;
}

const actions: ActionsType = {
	LOGIN_REQ : 'LOGIN_REQ',
	LOGOUT: 'LOGOUT',
	GET_USER : 'GET_USER',
	LOGGED_IN : 'LOGGED_IN',
	LOG_IN_ERR : 'LOG_IN_ERR',
	LOGOUT_SUCCESS : 'LOGOUT_SUCCESS',
	CATEGORIES : 'CATEGORIES',
	CATEGORIES_SUCCESS : 'CATEGORIES_SUCCESS',
	POSTS : 'POSTS',
	GET_POSTS_SUCCESS: 'GET_POSTS_SUCCESS',
	CREATE_POST: 'CREATE_POST',
	POST_CREATED: 'POST_CREATED',
	REDIRECT_HOME: 'REDIRECT_HOME',
	CREATE_CATEGORY : 'CREATE_CATEGORY',
	CATEGORY_CREATED : 'CATEGORY_CREATED',
	LIKE_POST : 'LIKE_POST',
	DISLIKE_POST : 'DISLIKE_POST',
	UPVOTE_POST : 'UPVOTE_POST',
	DOWNVOTE_POST : 'DOWNVOTE_POST',
	COMMENT_POST : 'COMMENT_POST',
	COMMENTS_UPDATE : 'COMMENTS_UPDATE',
	POST_REPORT : 'POST_REPORT',
	POST_SAVE : 'POST_SAVE',
	POST_SAVED : 'POST_SAVED',
	SET_SAVED_POSTS : 'SET_SAVED_POSTS',
	DELETE_POST : 'DELETE_POST'
}
export default actions;